deployment:
  tasks:
    # Paths
    - export REPOPATH=/home/quickerf/laravel_suites_repo/suites.quickerfaster.com
    - export DEPLOYPATH=/home/quickerf/public_html/suites.quickerfaster.com
    - export LOGDIR=/home/quickerf/deploy_logs
    - mkdir -p $LOGDIR
    - export LOGFILE=$LOGDIR/deploy_$(date +"%Y-%m-%d_%H-%M-%S").log

    # Start log
    - /bin/echo "===== Deployment started at $(date) =====" >> $LOGFILE

    # Pull latest changes from GitHub
    - /bin/echo "Pulling latest changes from GitHub..." >> $LOGFILE
    - cd $REPOPATH && /usr/bin/git pull origin main >> $LOGFILE 2>&1

    # Simulate rsync --delete (preserve exclusions)
    - /bin/echo "Cleaning destination folder..." >> $LOGFILE
    - /bin/sh -c 'for f in $(/bin/ls -A "$DEPLOYPATH"); do
        [ "$f" = ".env" ] || [ "$f" = ".cpanel.yml" ] || /bin/rm -rf "$DEPLOYPATH/$f";
      done' >> $LOGFILE 2>&1

    # Copy files with cp (preserve attributes)
    - /bin/echo "Copying files with cp..." >> $LOGFILE
    - /bin/sh -c 'cd "$REPOPATH" && /bin/cp -a $(/bin/ls -A | grep -vE "^(\.git|\.env|\.cpanel\.yml)$") "$DEPLOYPATH"' >> $LOGFILE 2>&1

    # Install Composer locally if missing
    - /bin/echo "Checking Composer..." >> $LOGFILE
    - /bin/sh -c 'if [ ! -f "$DEPLOYPATH/composer.phar" ]; then
        /bin/echo "Downloading Composer..." >> "$LOGFILE" &&
        cd "$DEPLOYPATH" &&
        /usr/bin/curl -sS https://getcomposer.org/installer | php >> "$LOGFILE" 2>&1;
      fi'

    # Install PHP dependencies using local composer.phar
    - /bin/echo "Installing PHP dependencies..." >> $LOGFILE
    - cd $DEPLOYPATH && php composer.phar install --no-dev --optimize-autoloader >> $LOGFILE 2>&1

    # Run migrations
    - /bin/echo "Running migrations..." >> $LOGFILE
    - php $DEPLOYPATH/artisan migrate --force >> $LOGFILE 2>&1

    # Run seeders
    - /bin/echo "Seeding database..." >> $LOGFILE
    - php $DEPLOYPATH/artisan db:seed --force >> $LOGFILE 2>&1

    # Clear caches
    - /bin/echo "Clearing caches..." >> $LOGFILE
    - php $DEPLOYPATH/artisan optimize:clear >> $LOGFILE 2>&1

    # End log
    - /bin/echo "===== Deployment finished at $(date) =====" >> $LOGFILE

    # Rotate logs - keep only last 5
    - /bin/ls -1t $LOGDIR/deploy_*.log | /usr/bin/tail -n +6 | /usr/bin/xargs -r /bin/rm --
