---
deployment:
  tasks:
    # Set environment variables
    - export REPOPATH="$HOME/laravel_suites_repo/suites.quickerfaster.com"
    - export DEPLOYPATH="$HOME/public_html/suites.quickerfaster.com"
    - export LOGDIR="$HOME/deploy_logs"
    - export LOGFILE="$LOGDIR/deploy_$(date +'%Y-%m-%d_%H-%M-%S').log"
    
    # Create directories
    - mkdir -p "$LOGDIR"
    - mkdir -p "$DEPLOYPATH"
    
    # Start deployment log
    - echo "===== Deployment started at $(date) =====" >> "$LOGFILE"
    
    # Update repository
    - echo "Pulling latest changes from GitHub..." >> "$LOGFILE"
    - cd "$REPOPATH" && git pull origin main >> "$LOGFILE" 2>&1
    
    # Clean deployment directory (preserve .env and .cpanel.yml)
    - echo "Cleaning destination folder..." >> "$LOGFILE"
    - find "$DEPLOYPATH" -mindepth 1 \
        ! -name '.env' \
        ! -name '.cpanel.yml' \
        -exec rm -rf {} + >> "$LOGFILE" 2>&1
    
    # Copy files using tar (fixed version)
    - echo "Copying files using tar..." >> "$LOGFILE"
    - cd "$REPOPATH" && /bin/tar \
        --exclude=".git" \
        --exclude=".cpanel.yml" \
        --exclude=".env" \
        -cf - . \
      | (cd "$DEPLOYPATH" && /bin/tar -xf -) >> "$LOGFILE" 2>&1
    
    # Install dependencies
    - echo "Installing PHP dependencies..." >> "$LOGFILE"
    - /opt/cpanel/composer/bin/composer install \
        --no-dev \
        --optimize-autoloader \
        --working-dir="$DEPLOYPATH" >> "$LOGFILE" 2>&1
    
    # Run database migrations
    - echo "Running migrations..." >> "$LOGFILE"
    - /opt/cpanel/php/bin/php "$DEPLOYPATH/artisan" migrate --force >> "$LOGFILE" 2>&1
    
    # Seed database
    - echo "Seeding database..." >> "$LOGFILE"
    - /opt/cpanel/php/bin/php "$DEPLOYPATH/artisan" db:seed --force >> "$LOGFILE" 2>&1
    
    # Optimize application
    - echo "Clearing caches..." >> "$LOGFILE"
    - /opt/cpanel/php/bin/php "$DEPLOYPATH/artisan" optimize:clear >> "$LOGFILE" 2>&1
    
    # Finalize deployment
    - echo "===== Deployment finished at $(date) =====" >> "$LOGFILE"
    
    # Rotate logs (keep last 5)
    - ls -1t "$LOGDIR"/deploy_*.log | tail -n +6 | xargs -r rm -- >> "$LOGFILE" 2>&1