---
deployment:
  tasks:
    # Paths
    - export REPOPATH=/home/quickerf/laravel_suites_repo/suites.quickerfaster.com
    - export DEPLOYPATH=/home/quickerf/public_html/suites.quickerfaster.com
    - export LOGDIR=/home/quickerf/deploy_logs
    - mkdir -p $LOGDIR
    - export LOGFILE=$LOGDIR/deploy_$(date +"%Y-%m-%d_%H-%M-%S").log

    # Start log
    - /bin/echo "===== Deployment started at $(date) =====" >> $LOGFILE

    # Change to repo subfolder and pull latest changes
    - /bin/echo "Pulling latest changes from GitHub..." >> $LOGFILE
    - cd $REPOPATH && /usr/bin/git pull origin main >> $LOGFILE 2>&1

    # Simulate rsync --delete (remove old files except excluded ones)
    - /bin/echo "Cleaning destination folder..." >> $LOGFILE
    - /bin/bash -c "find \"$DEPLOYPATH\" -mindepth 1 \
        -not -name '.env' \
        -not -name '.cpanel.yml' \
        -not -path \"$DEPLOYPATH/.git*\" \
        -exec rm -rf {} + " >> $LOGFILE 2>&1


    # Copy files using tar with exclusions
    - /bin/echo "Copying files using tar..." >> $LOGFILE
    - tar --exclude=".git" \
          --exclude=".cpanel.yml" \
          --exclude=".env" \
          -cf - -C $REPOPATH . | tar -xf - -C $DEPLOYPATH >> $LOGFILE 2>&1

    # Install PHP dependencies
    - /bin/echo "Installing PHP dependencies..." >> $LOGFILE
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader --working-dir=$DEPLOYPATH >> $LOGFILE 2>&1

    # Run migrations
    - /bin/echo "Running migrations..." >> $LOGFILE
    - /opt/cpanel/php/bin/php $DEPLOYPATH/artisan migrate --force >> $LOGFILE 2>&1

    # Run seeders
    - /bin/echo "Seeding database..." >> $LOGFILE
    - /opt/cpanel/php/bin/php $DEPLOYPATH/artisan db:seed --force >> $LOGFILE 2>&1

    # Clear caches
    - /bin/echo "Clearing caches..." >> $LOGFILE
    - /opt/cpanel/php/bin/php $DEPLOYPATH/artisan optimize:clear >> $LOGFILE 2>&1

    # End log
    - /bin/echo "===== Deployment finished at $(date) =====" >> $LOGFILE

    # Rotate logs - keep only last 5
    - /bin/ls -1t $LOGDIR/deploy_*.log | /usr/bin/tail -n +6 | /usr/bin/xargs -r /bin/rm --
