deployment:
  tasks:
    # Paths
    - export COMPOSER_BIN=/home/quickerf/composer.phar
    - export REPOPATH=/home/quickerf/laravel_suites_repo/suites.quickerfaster.com
    - export DEPLOYPATH=/home/quickerf/public_html/suites.quickerfaster.com
    - export LOGDIR=/home/quickerf/deploy_logs
    - mkdir -p $LOGDIR
    - export LOGFILE=$LOGDIR/deploy_$(date +"%Y-%m-%d_%H-%M-%S").log

    # Start log
    - /bin/echo "===== Deployment started at $(date) =====" >> $LOGFILE

    # Pull latest changes from GitHub
    - /bin/echo "Pulling latest changes from GitHub..." >> $LOGFILE
    - cd $REPOPATH && /usr/bin/git pull origin main >> $LOGFILE 2>&1

    # Clean destination folder but preserve .env and .cpanel.yml
    - /bin/echo "Cleaning destination folder..." >> $LOGFILE
    - /bin/sh -c 'for f in $(/bin/ls -A "$DEPLOYPATH"); do
        [ "$f" = ".env" ] || [ "$f" = ".cpanel.yml" ] || /bin/rm -rf "$DEPLOYPATH/$f";
      done' >> $LOGFILE 2>&1

    # Copy repository files to destination
    - /bin/echo "Copying files to deployment path..." >> $LOGFILE
    - /bin/sh -c 'cd "$REPOPATH" && /bin/cp -a $(/bin/ls -A | grep -vE "^(\.git|\.env|\.cpanel\.yml)$") "$DEPLOYPATH"' >> $LOGFILE 2>&1

    # Ensure Laravel storage and cache directories exist
    - /bin/echo "Ensuring Laravel storage and cache folders exist..." >> $LOGFILE
    - /bin/sh -c 'mkdir -p $DEPLOYPATH/storage/framework/cache/data \
                   $DEPLOYPATH/storage/framework/sessions \
                   $DEPLOYPATH/storage/framework/views \
                   $DEPLOYPATH/bootstrap/cache \
                   $DEPLOYPATH/storage/logs' >> $LOGFILE 2>&1


    # Install Composer locally if missing
    - /bin/echo "Checking Composer..." >> $LOGFILE
    - /bin/sh -c 'if [ ! -f "$COMPOSER_BIN" ]; then
        /bin/echo "Downloading Composer..." >> $LOGFILE &&
        cd /home/quickerf &&
        /usr/bin/curl -sS https://getcomposer.org/installer -o composer-setup.php &&
        php composer-setup.php --quiet &&
        rm composer-setup.php &&
        /bin/echo "Composer installed successfully" >> $LOGFILE;
      fi'

    # Install PHP dependencies using local Composer
    - /bin/echo "Installing PHP dependencies..." >> $LOGFILE
    - /bin/sh -c 'cd "$DEPLOYPATH" && php "$COMPOSER_BIN" install --no-dev --optimize-autoloader >> "$LOGFILE" 2>&1'

    # Run Laravel migrations
    - /bin/echo "Running migrations..." >> $LOGFILE
    - /bin/sh -c 'php "$DEPLOYPATH/artisan" migrate --force >> "$LOGFILE" 2>&1'

    # Seed database
    - /bin/echo "Seeding database..." >> $LOGFILE
    - /bin/sh -c 'php "$DEPLOYPATH/artisan" db:seed --force >> "$LOGFILE" 2>&1'

    # Clear caches
    - /bin/echo "Clearing caches..." >> $LOGFILE
    - /bin/sh -c 'php "$DEPLOYPATH/artisan" optimize:clear >> "$LOGFILE" 2>&1'

    # End log
    - /bin/echo "===== Deployment finished at $(date) =====" >> $LOGFILE

    # Rotate logs - keep only last 5
    - /bin/ls -1t $LOGDIR/deploy_*.log | /usr/bin/tail -n +6 | /usr/bin/xargs -r /bin/rm --
