---
deployment:
  tasks:
    - export DEPLOYPATH=/home/quickerf/public_html/suites.quickerfaster.com
    - /bin/echo "Syncing files to public_html..."
    - /bin/rsync -av --delete --exclude=".git" --exclude=".cpanel.yml" --exclude=".env" ./ $DEPLOYPATH
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader --working-dir=$DEPLOYPATH
    - /opt/cpanel/php/bin/php $DEPLOYPATH/artisan migrate --force
    - /opt/cpanel/php/bin/php $DEPLOYPATH/artisan db:seed --force
    - /opt/cpanel/php/bin/php $DEPLOYPATH/artisan optimize:clear
