models:
  ReturnOrder:
    module: order # Or a more appropriate module name
    fields:
      return_number:
        type: string
        validation:
          - required|unique:returns,return_number
      sales_order_id:
        type: select
        foreign:
          table: sales_orders
          column: id
          onDelete: cascade
      purchase_order_id:
        type: select
        foreign:
          table: purchase_orders
          column: id
          onDelete: cascade
      customer_profile_id:
        type: select
        foreign:
          table: customer_profiles
          column: id
          onDelete: cascade
      supplier_profile_id:
        type: select
        foreign:
          table: supplier_profiles
          column: id
          onDelete: cascade
      status:
        type: select
        options: pending, approved, rejected
        default: pending
      created_by:
        type: select
        validation:
          - required
        foreign:
          table: users
          column: id
          onDelete: cascade
      approved_by:
        type: select
        foreign:
          table: users
          column: id
          onDelete: set null
      approved_at:
        type: datetime
      reason:
        type: textarea # Or string if you prefer a single line

    hiddenFields:
      onTable: []
      onNewForm: [status, created_by, approved_by, approved_at, items]
      onEditForm: [created_by, approved_by, approved_at, items]
      onQuery: []

    auditTrail:
      - created
      - approved # Or other relevant events

    tab:
      label: Return Orders
      group: return-order-management
      id: returned-orders
      parentPageTitle: Returned Orders Management
      pageTitle: Returned Orders
      view: returned-orders
      url: order/returned-orders # Adjust URL as needed

    fieldGroups:
      - title: Return Info
        groupType: hr
        fields:
          - return_number
          - sales_order_id
          - purchase_order_id
          - customer_profile_id
          - supplier_profile_id
          - status
          - reason

      - title: Audit Trait
        groupType: hr
        fields:
          - created_by
          - approved_by
          - created_at
          - approved_at

    relations:
      salesOrder:
        type: belongsTo
        model: App\Modules\Sales\Models\SalesOrder # Correct namespace
        foreignKey: sales_order_id
        displayField: order_number

      purchaseOrder:
        type: belongsTo
        model: App\Modules\Order\Models\PurchaseOrder # Correct namespace
        foreignKey: purchase_order_id
        displayField: order_number

      customerProfile:
        type: belongsTo
        model: App\Models\CustomerProfile # Correct namespace
        foreignKey: customer_profile_id
        displayField: user.name

      supplierProfile:
        type: belongsTo
        model: App\Models\SupplierProfile # Correct namespace
        foreignKey: supplier_profile_id
        displayField: user.name

      createdBy:
        type: belongsTo
        model: App\Models\User
        foreignKey: created_by

      approvedBy:
        type: belongsTo
        model: App\Models\User
        foreignKey: approved_by

      items:
        type: belongsToMany
        model: App\Modules\Item\Models\Item  # Correct namespace for Item
        pivotTable: return_order_items
        foreignKey: return_order_id
        localKey: item_id
        #using: App\Modules\Order\Models\ReturnItem # Assuming Inventory module for pivot model

    sidebar:
      add: true
      title: Returned Orders
      iconClasses: fas fa-undo # Or a more suitable icon
      url: returned-orders

    iconClasses: fas fa-undo # Or a more suitable icon
    includeHeader: true
    includeFooter: true
    includeSidebar: true
    controls: all
    simpleActions: ['show', 'edit', 'delete']

  ReturnOrderItem:
    module: order # Or a more appropriate module name
    fields:
      return_order_id:
        type: select
        validation:
          - required
        foreign:
          table: return_orders
          column: id
          onDelete: cascade
      item_id:
        type: select
        validation:
          - required
        foreign:
          table: items
          column: id
          onDelete: cascade
      quantity:
        type: decimal
        validation:
          - required

    hiddenFields:
      onTable: []
      onNewForm: [] # Customize as needed
      onEditForm: [] # Customize as needed
      onQuery: []

    tab:
      label: Returned Items
      group: return-order-management
      id: returned-items
      parentPageTitle: Returned Orders Management
      pageTitle: Returned Items
      view: returned-items
      url: order/returned-items # Adjust URL as needed

    fieldGroups:
      - title: Return Info
        groupType: hr
        fields:
          - return_oredr_id

      - title: Item Details
        groupType: hr
        fields:
          - item_id
          - quantity

    relations:
      returnOrder:
        type: belongsTo
        model: App\Modules\Order\Models\ReturnOrder  # Correct namespace
        foreignKey: return_order_id
        displayField: return_number

      item:
        type: belongsTo
        model: App\Modules\Item\Models\Item  # Correct namespace
        foreignKey: item_id

    iconClasses: fas fa-list-alt # Or a more suitable icon
    sidebar:
      add: false
    includeHeader: true
    includeFooter: true
    includeSidebar: true
    controls: all
    simpleActions: ['show', 'edit', 'delete']
