<?php

return [
    [
    'title' => 'Departments',
    'icon' => 'fas fa-building',
    'url' => 'hr/departments',
    'permission' => 'view_department',
    'key' => 'department',
],
    [
    'title' => 'Job Titles',
    'icon' => 'fas fa-heading',
    'url' => 'hr/job-titles',
    'permission' => 'view_job_title',
    'key' => 'job_title',
],
    [
    'title' => 'Employees',
    'icon' => 'fas fa-users',
    'url' => 'hr/employees',
    'permission' => 'view_employee',
    'key' => 'employee',
],
    [
    'title' => 'Employee Positions',
    'icon' => 'fas fa-suitcase',
    'url' => 'hr/employee-positions',
    'permission' => 'view_employee_position',
    'key' => 'employee_position',
],
    [
    'title' => 'Employee Profiles',
    'icon' => 'fas fa-user-tie',
    'url' => 'hr/employee-profiles',
    'permission' => 'view_employee_profile',
    'key' => 'employee_profile',
],
    [
    'title' => 'Documents',
    'icon' => 'fas fa-file-alt',
    'url' => 'hr/documents',
    'permission' => 'view_document',
    'key' => 'document',
],
    [
    'title' => 'Pay Schedules',
    'icon' => 'fas fa-clock',
    'url' => 'hr/pay-schedules',
    'permission' => 'view_pay_schedule',
    'key' => 'pay_schedule',
],
    [
    'title' => 'Employee Payroll Profiles',
    'icon' => 'fas fa-user-tie',
    'url' => 'hr/employee-payroll-profiles',
    'permission' => 'view_employee_payroll_profile',
    'key' => 'employee_payroll_profile',
],
    [
    'title' => 'Payroll Runs',
    'icon' => 'fas fa-money-bill-wave',
    'url' => 'hr/payroll-runs',
    'permission' => 'view_payroll_run',
    'key' => 'payroll_run',
],
    [
    'title' => 'Payroll Payslips',
    'icon' => 'fas fa-receipt',
    'url' => 'hr/payroll-payslips',
    'permission' => 'view_payroll_payslip',
    'key' => 'payroll_payslip',
],
    [
    'title' => 'Clock Events',
    'icon' => 'fas fa-clock-events',
    'url' => 'hr/clock-events',
    'permission' => 'view_clock_event',
    'key' => 'clock_event',
],
    [
    'title' => 'Attendances',
    'icon' => 'fas fa-user-clock',
    'url' => 'hr/attendances',
    'permission' => 'view_attendance',
    'key' => 'attendance',
],
    [
    'title' => 'Shifts',
    'icon' => 'fas fa-clock',
    'url' => 'hr/shifts',
    'permission' => 'view_shift',
    'key' => 'shift',
],
    [
    'title' => 'Timesheets',
    'icon' => 'fas fa-table',
    'url' => 'hr/timesheets',
    'permission' => 'view_timesheet',
    'key' => 'timesheet',
],
    [
    'title' => 'Timesheet Entries',
    'icon' => 'fas fa-gift',
    'url' => 'hr/timesheet-entries',
    'permission' => 'view_timesheet_entry',
    'key' => 'timesheet_entry',
],
    [
    'title' => 'Holiday Calendars',
    'icon' => 'fas fa-calendar-alt',
    'url' => 'hr/holiday-calendars',
    'permission' => 'view_holiday_calendar',
    'key' => 'holiday_calendar',
],
    [
    'title' => 'Holidays',
    'icon' => 'fas fa-gift',
    'url' => 'hr/holidays',
    'permission' => 'view_holiday',
    'key' => 'holiday',
],
];
